  //COMPILALL JOB (BANK),'COMPILE ALL COBOL PROGRAMS',
  //          CLASS=A,MSGCLASS=A,MSGLEVEL=(1,1),
  //          NOTIFY=&SYSUID
  //*
  //*================================================================*
  //* JOB: COMPILALL                                                  *
  //* PURPOSE: COMPILE ALL BANKING PROGRAMS IN DEPENDENCY ORDER       *
  //* USES: OS/VS COBOL COMPILER (IGYCRCTL) VIA TK4-                  *
  //*       ADJUST SYS1.COBOL AND SYS1.COPYLIB TO YOUR PDS NAMES     *
  //*================================================================*
  //*
  //*--- COMPILE DATEVAL (utility, no VSAM deps) ----------------
  //COMP01   EXEC PGM=IGYCRCTL,REGION=512K,
  //         PARM='NOSSRANGE,NOSEQUENCE,NODECK,OBJECT,XREF'
  //STEPLIB  DD DSN=SYS1.COBLIB,DISP=SHR
  //SYSPRINT DD SYSOUT=*
  //SYSIN    DD DSN=SYS1.COBOL(DATEVAL),DISP=SHR
  //SYSLIB   DD DSN=SYS1.COPYLIB,DISP=SHR
  //SYSUT1   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT2   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT3   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT4   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSLIN   DD DSN=&&DATEVAL,DISP=(NEW,PASS),
  //         UNIT=SYSDA,SPACE=(TRK,(10,5))
  //*
  //*--- LINK DATEVAL -------------------------------------------
  //LKED01   EXEC PGM=IEWL,REGION=512K,COND=(5,LT,COMP01),
  //         PARM='LIST,XREF,LET'
  //SYSPRINT DD SYSOUT=*
  //SYSLIN   DD DSN=&&DATEVAL,DISP=(OLD,DELETE)
  //SYSLMOD  DD DSN=SYS1.BANKLOAD(DATEVAL),DISP=SHR
  //SYSUT1   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //*
  //*--- COMPILE ERRHANDL ---------------------------------------
  //COMP02   EXEC PGM=IGYCRCTL,REGION=512K,
  //         PARM='NOSSRANGE,NOSEQUENCE,NODECK,OBJECT,XREF'
  //STEPLIB  DD DSN=SYS1.COBLIB,DISP=SHR
  //SYSPRINT DD SYSOUT=*
  //SYSIN    DD DSN=SYS1.COBOL(ERRHANDL),DISP=SHR
  //SYSLIB   DD DSN=SYS1.COPYLIB,DISP=SHR
  //SYSUT1   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT2   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT3   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT4   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSLIN   DD DSN=&&ERRHANDL,DISP=(NEW,PASS),
  //         UNIT=SYSDA,SPACE=(TRK,(10,5))
  //*
  //LKED02   EXEC PGM=IEWL,REGION=512K,COND=(5,LT,COMP02),
  //         PARM='LIST,XREF,LET'
  //SYSPRINT DD SYSOUT=*
  //SYSLIN   DD DSN=&&ERRHANDL,DISP=(OLD,DELETE)
  //SYSLMOD  DD DSN=SYS1.BANKLOAD(ERRHANDL),DISP=SHR
  //SYSUT1   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //*
  //*--- COMPILE CUSTMGMT ---------------------------------------
  //COMP03   EXEC PGM=IGYCRCTL,REGION=512K,
  //         PARM='NOSSRANGE,NOSEQUENCE,NODECK,OBJECT,XREF'
  //STEPLIB  DD DSN=SYS1.COBLIB,DISP=SHR
  //SYSPRINT DD SYSOUT=*
  //SYSIN    DD DSN=SYS1.COBOL(CUSTMGMT),DISP=SHR
  //SYSLIB   DD DSN=SYS1.COPYLIB,DISP=SHR
  //SYSUT1   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT2   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT3   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT4   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSLIN   DD DSN=&&CUSTMGMT,DISP=(NEW,PASS),
  //         UNIT=SYSDA,SPACE=(TRK,(10,5))
  //LKED03   EXEC PGM=IEWL,REGION=512K,COND=(5,LT,COMP03),
  //         PARM='LIST,XREF,LET'
  //SYSPRINT DD SYSOUT=*
  //SYSLIN   DD DSN=&&CUSTMGMT,DISP=(OLD,DELETE)
  //         DD DSN=SYS1.BANKLOAD(DATEVAL),DISP=SHR
  //         DD DSN=SYS1.BANKLOAD(ERRHANDL),DISP=SHR
  //SYSLMOD  DD DSN=SYS1.BANKLOAD(CUSTMGMT),DISP=SHR
  //SYSUT1   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //*
  //*--- COMPILE ACCTMGMT ---------------------------------------
  //COMP04   EXEC PGM=IGYCRCTL,REGION=512K,
  //         PARM='NOSSRANGE,NOSEQUENCE,NODECK,OBJECT,XREF'
  //STEPLIB  DD DSN=SYS1.COBLIB,DISP=SHR
  //SYSPRINT DD SYSOUT=*
  //SYSIN    DD DSN=SYS1.COBOL(ACCTMGMT),DISP=SHR
  //SYSLIB   DD DSN=SYS1.COPYLIB,DISP=SHR
  //SYSUT1   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT2   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT3   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT4   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSLIN   DD DSN=&&ACCTMGMT,DISP=(NEW,PASS),
  //         UNIT=SYSDA,SPACE=(TRK,(10,5))
  //LKED04   EXEC PGM=IEWL,REGION=512K,COND=(5,LT,COMP04),
  //         PARM='LIST,XREF,LET'
  //SYSPRINT DD SYSOUT=*
  //SYSLIN   DD DSN=&&ACCTMGMT,DISP=(OLD,DELETE)
  //         DD DSN=SYS1.BANKLOAD(DATEVAL),DISP=SHR
  //         DD DSN=SYS1.BANKLOAD(ERRHANDL),DISP=SHR
  //SYSLMOD  DD DSN=SYS1.BANKLOAD(ACCTMGMT),DISP=SHR
  //SYSUT1   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //*
  //*--- COMPILE BATCHPROC + RPTGEN -------------------------------
  //COMP10   EXEC PGM=IGYCRCTL,REGION=512K,
  //         PARM='NOSSRANGE,NOSEQUENCE,NODECK,OBJECT,XREF'
  //STEPLIB  DD DSN=SYS1.COBLIB,DISP=SHR
  //SYSPRINT DD SYSOUT=*
  //SYSIN    DD DSN=SYS1.COBOL(BATCHPROC),DISP=SHR
  //SYSLIB   DD DSN=SYS1.COPYLIB,DISP=SHR
  //SYSUT1   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT2   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT3   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT4   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSLIN   DD DSN=&&BATCHPROC,DISP=(NEW,PASS),
  //         UNIT=SYSDA,SPACE=(TRK,(20,5))
  //LKED10   EXEC PGM=IEWL,REGION=512K,COND=(5,LT,COMP10),
  //         PARM='LIST,XREF,LET'
  //SYSPRINT DD SYSOUT=*
  //SYSLIN   DD DSN=&&BATCHPROC,DISP=(OLD,DELETE)
  //         DD DSN=SYS1.BANKLOAD(DATEVAL),DISP=SHR
  //         DD DSN=SYS1.BANKLOAD(ERRHANDL),DISP=SHR
  //SYSLMOD  DD DSN=SYS1.BANKLOAD(BATCHPROC),DISP=SHR
  //SYSUT1   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //*--- COMPILE RPTGEN ----------------------------------------
  //COMP11   EXEC PGM=IGYCRCTL,REGION=512K,
  //         PARM='NOSSRANGE,NOSEQUENCE,NODECK,OBJECT,XREF'
  //STEPLIB  DD DSN=SYS1.COBLIB,DISP=SHR
  //SYSPRINT DD SYSOUT=*
  //SYSIN    DD DSN=SYS1.COBOL(RPTGEN),DISP=SHR
  //SYSLIB   DD DSN=SYS1.COPYLIB,DISP=SHR
  //SYSUT1   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT2   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT3   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT4   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSLIN   DD DSN=&&RPTGEN,DISP=(NEW,PASS),
  //         UNIT=SYSDA,SPACE=(TRK,(10,5))
  //LKED11   EXEC PGM=IEWL,REGION=512K,COND=(5,LT,COMP11),
  //         PARM='LIST,XREF,LET'
  //SYSPRINT DD SYSOUT=*
  //SYSLIN   DD DSN=&&RPTGEN,DISP=(OLD,DELETE)
  //         DD DSN=SYS1.BANKLOAD(DATEVAL),DISP=SHR
  //         DD DSN=SYS1.BANKLOAD(ERRHANDL),DISP=SHR
  //SYSLMOD  DD DSN=SYS1.BANKLOAD(RPTGEN),DISP=SHR
  //SYSUT1   DD UNIT=SYSDA,SPACE=(CYL,(1,1))

  //*--- COMPILE ACCTBLCK -------------------------------------
  //COMP05   EXEC PGM=IGYCRCTL,REGION=512K,
  //         PARM='NOSSRANGE,NOSEQUENCE,NODECK,OBJECT,XREF'
  //STEPLIB  DD DSN=SYS1.COBLIB,DISP=SHR
  //SYSPRINT DD SYSOUT=*
  //SYSIN    DD DSN=SYS1.COBOL(ACCTBLCK),DISP=SHR
  //SYSLIB   DD DSN=SYS1.COPYLIB,DISP=SHR
  //SYSUT1   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT2   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT3   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT4   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSLIN   DD DSN=&&ACCTBLCK,DISP=(NEW,PASS),
  //         UNIT=SYSDA,SPACE=(TRK,(10,5))
  //LKED05   EXEC PGM=IEWL,REGION=512K,COND=(5,LT,COMP05),
  //         PARM='LIST,XREF,LET'
  //SYSPRINT DD SYSOUT=*
  //SYSLIN   DD DSN=&&ACCTBLCK,DISP=(OLD,DELETE)
  //         DD DSN=SYS1.BANKLOAD(DATEVAL),DISP=SHR
  //         DD DSN=SYS1.BANKLOAD(ERRHANDL),DISP=SHR
  //SYSLMOD  DD DSN=SYS1.BANKLOAD(ACCTBLCK),DISP=SHR
  //SYSUT1   DD UNIT=SYSDA,SPACE=(CYL,(1,1))

  //*--- COMPILE BALANCIO -------------------------------------
  //COMP06   EXEC PGM=IGYCRCTL,REGION=512K,
  //         PARM='NOSSRANGE,NOSEQUENCE,NODECK,OBJECT,XREF'
  //STEPLIB  DD DSN=SYS1.COBLIB,DISP=SHR
  //SYSPRINT DD SYSOUT=*
  //SYSIN    DD DSN=SYS1.COBOL(BALANCIO),DISP=SHR
  //SYSLIB   DD DSN=SYS1.COPYLIB,DISP=SHR
  //SYSUT1   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT2   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT3   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT4   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSLIN   DD DSN=&&BALANCIO,DISP=(NEW,PASS),
  //         UNIT=SYSDA,SPACE=(TRK,(10,5))
  //LKED06   EXEC PGM=IEWL,REGION=512K,COND=(5,LT,COMP06),
  //         PARM='LIST,XREF,LET'
  //SYSPRINT DD SYSOUT=*
  //SYSLIN   DD DSN=&&BALANCIO,DISP=(OLD,DELETE)
  //         DD DSN=SYS1.BANKLOAD(DATEVAL),DISP=SHR
  //         DD DSN=SYS1.BANKLOAD(ERRHANDL),DISP=SHR
  //SYSLMOD  DD DSN=SYS1.BANKLOAD(BALANCIO),DISP=SHR
  //SYSUT1   DD UNIT=SYSDA,SPACE=(CYL,(1,1))

  //*--- COMPILE DEPOSIT --------------------------------------
  //COMP07   EXEC PGM=IGYCRCTL,REGION=512K,
  //         PARM='NOSSRANGE,NOSEQUENCE,NODECK,OBJECT,XREF'
  //STEPLIB  DD DSN=SYS1.COBLIB,DISP=SHR
  //SYSPRINT DD SYSOUT=*
  //SYSIN    DD DSN=SYS1.COBOL(DEPOSIT),DISP=SHR
  //SYSLIB   DD DSN=SYS1.COPYLIB,DISP=SHR
  //SYSUT1   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT2   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT3   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT4   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSLIN   DD DSN=&&DEPOSIT,DISP=(NEW,PASS),
  //         UNIT=SYSDA,SPACE=(TRK,(10,5))
  //LKED07   EXEC PGM=IEWL,REGION=512K,COND=(5,LT,COMP07),
  //         PARM='LIST,XREF,LET'
  //SYSPRINT DD SYSOUT=*
  //SYSLIN   DD DSN=&&DEPOSIT,DISP=(OLD,DELETE)
  //         DD DSN=SYS1.BANKLOAD(DATEVAL),DISP=SHR
  //         DD DSN=SYS1.BANKLOAD(ERRHANDL),DISP=SHR
  //SYSLMOD  DD DSN=SYS1.BANKLOAD(DEPOSIT),DISP=SHR
  //SYSUT1   DD UNIT=SYSDA,SPACE=(CYL,(1,1))

  //*--- COMPILE WITHDRAW -------------------------------------
  //COMP08   EXEC PGM=IGYCRCTL,REGION=512K,
  //         PARM='NOSSRANGE,NOSEQUENCE,NODECK,OBJECT,XREF'
  //STEPLIB  DD DSN=SYS1.COBLIB,DISP=SHR
  //SYSPRINT DD SYSOUT=*
  //SYSIN    DD DSN=SYS1.COBOL(WITHDRAW),DISP=SHR
  //SYSLIB   DD DSN=SYS1.COPYLIB,DISP=SHR
  //SYSUT1   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT2   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT3   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT4   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSLIN   DD DSN=&&WITHDRAW,DISP=(NEW,PASS),
  //         UNIT=SYSDA,SPACE=(TRK,(10,5))
  //LKED08   EXEC PGM=IEWL,REGION=512K,COND=(5,LT,COMP08),
  //         PARM='LIST,XREF,LET'
  //SYSPRINT DD SYSOUT=*
  //SYSLIN   DD DSN=&&WITHDRAW,DISP=(OLD,DELETE)
  //         DD DSN=SYS1.BANKLOAD(DATEVAL),DISP=SHR
  //         DD DSN=SYS1.BANKLOAD(ERRHANDL),DISP=SHR
  //SYSLMOD  DD DSN=SYS1.BANKLOAD(WITHDRAW),DISP=SHR
  //SYSUT1   DD UNIT=SYSDA,SPACE=(CYL,(1,1))

  //*--- COMPILE TRANSFER -------------------------------------
  //COMP09   EXEC PGM=IGYCRCTL,REGION=512K,
  //         PARM='NOSSRANGE,NOSEQUENCE,NODECK,OBJECT,XREF'
  //STEPLIB  DD DSN=SYS1.COBLIB,DISP=SHR
  //SYSPRINT DD SYSOUT=*
  //SYSIN    DD DSN=SYS1.COBOL(TRANSFER),DISP=SHR
  //SYSLIB   DD DSN=SYS1.COPYLIB,DISP=SHR
  //SYSUT1   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT2   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT3   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT4   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSLIN   DD DSN=&&TRANSFER,DISP=(NEW,PASS),
  //         UNIT=SYSDA,SPACE=(TRK,(10,5))
  //LKED09   EXEC PGM=IEWL,REGION=512K,COND=(5,LT,COMP09),
  //         PARM='LIST,XREF,LET'
  //SYSPRINT DD SYSOUT=*
  //SYSLIN   DD DSN=&&TRANSFER,DISP=(OLD,DELETE)
  //         DD DSN=SYS1.BANKLOAD(DATEVAL),DISP=SHR
  //         DD DSN=SYS1.BANKLOAD(ERRHANDL),DISP=SHR
  //SYSLMOD  DD DSN=SYS1.BANKLOAD(TRANSFER),DISP=SHR
  //SYSUT1   DD UNIT=SYSDA,SPACE=(CYL,(1,1))

  //*--- COMPILE TRANHIST -------------------------------------
  //COMP12   EXEC PGM=IGYCRCTL,REGION=512K,
  //         PARM='NOSSRANGE,NOSEQUENCE,NODECK,OBJECT,XREF'
  //STEPLIB  DD DSN=SYS1.COBLIB,DISP=SHR
  //SYSPRINT DD SYSOUT=*
  //SYSIN    DD DSN=SYS1.COBOL(TRANHIST),DISP=SHR
  //SYSLIB   DD DSN=SYS1.COPYLIB,DISP=SHR
  //SYSUT1   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT2   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT3   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT4   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSLIN   DD DSN=&&TRANHIST,DISP=(NEW,PASS),
  //         UNIT=SYSDA,SPACE=(TRK,(10,5))
  //LKED12   EXEC PGM=IEWL,REGION=512K,COND=(5,LT,COMP12),
  //         PARM='LIST,XREF,LET'
  //SYSPRINT DD SYSOUT=*
  //SYSLIN   DD DSN=&&TRANHIST,DISP=(OLD,DELETE)
  //         DD DSN=SYS1.BANKLOAD(DATEVAL),DISP=SHR
  //         DD DSN=SYS1.BANKLOAD(ERRHANDL),DISP=SHR
  //SYSLMOD  DD DSN=SYS1.BANKLOAD(TRANHIST),DISP=SHR
  //SYSUT1   DD UNIT=SYSDA,SPACE=(CYL,(1,1))

  //*--- COMPILE BANKMENU (main program, last) -----------------
  //COMP13   EXEC PGM=IGYCRCTL,REGION=512K,
  //         PARM='NOSSRANGE,NOSEQUENCE,NODECK,OBJECT,XREF'
  //STEPLIB  DD DSN=SYS1.COBLIB,DISP=SHR
  //SYSPRINT DD SYSOUT=*
  //SYSIN    DD DSN=SYS1.COBOL(BANKMENU),DISP=SHR
  //SYSLIB   DD DSN=SYS1.COPYLIB,DISP=SHR
  //SYSUT1   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT2   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT3   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSUT4   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
  //SYSLIN   DD DSN=&&BANKMENU,DISP=(NEW,PASS),
  //         UNIT=SYSDA,SPACE=(TRK,(20,5))
  //LKED13   EXEC PGM=IEWL,REGION=512K,COND=(5,LT,COMP13),
  //         PARM='LIST,XREF,LET'
  //SYSPRINT DD SYSOUT=*
  //SYSLIN   DD DSN=&&BANKMENU,DISP=(OLD,DELETE)
  //         DD DSN=SYS1.BANKLOAD(DATEVAL),DISP=SHR
  //         DD DSN=SYS1.BANKLOAD(ERRHANDL),DISP=SHR
  //         DD DSN=SYS1.BANKLOAD(ACCTBLCK),DISP=SHR
  //         DD DSN=SYS1.BANKLOAD(CUSTMGMT),DISP=SHR
  //         DD DSN=SYS1.BANKLOAD(ACCTMGMT),DISP=SHR
  //         DD DSN=SYS1.BANKLOAD(BALANCIO),DISP=SHR
  //         DD DSN=SYS1.BANKLOAD(DEPOSIT),DISP=SHR
  //         DD DSN=SYS1.BANKLOAD(WITHDRAW),DISP=SHR
  //         DD DSN=SYS1.BANKLOAD(TRANSFER),DISP=SHR
  //         DD DSN=SYS1.BANKLOAD(TRANHIST),DISP=SHR
  //         DD DSN=SYS1.BANKLOAD(RPTGEN),DISP=SHR
  //SYSLMOD  DD DSN=SYS1.BANKLOAD(BANKMENU),DISP=SHR
  //SYSUT1   DD UNIT=SYSDA,SPACE=(CYL,(1,1))
